name: Run Unit Tests

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - '**'  # Run on all branches

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: postgresql+asyncpg://test:test@localhost:5432/test_db
      SECRET_KEY: test-secret-key-for-testing-only
      ALGORITHM: HS256
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Run tests
      run: |
        pytest tests/ -v
